src/Entity/Eleve.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EleveRepository")
 */
class Eleve
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $Matricule;

    /**
     * @ORM\Column(type="text")
     */
    private $Prenoms;

    /**
     * @ORM\Column(type="text")
     */
    private $Nom;

    /**
     * @ORM\Column(type="text")
     */
    private $PaysDeNaissance;

    /**
     * @ORM\Column(type="text")
     */
    private $LieuDeNaissance;

    /**
     * @ORM\Column(type="date")
     */
    private $DateDeNaissance;

    /**
     * @ORM\Column(type="text")
     */
    private $Sexe;

    /**
     * @ORM\Column(type="text")
     */
    private $AdresseDeResidence;

    /**
     * @ORM\Column(type="integer")
     */
    private $TelephoneDomicile;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $TelephoneEleve;

    /**
     * @ORM\Column(type="date")
     */
    private $AnneeDarrivee;


    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $PetitFrereOuSoeur;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $FrereOuSoeur;

    /**
     * @ORM\Column(type="text")
     */
    private $PreferenceManuel;

    /**
     * @ORM\Column(type="text")
     */
    private $TolerenceParacetamol;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $MaladieSignale;

    /**
     * @ORM\Column(type="integer")
     */
    private $CodeFamille;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Parents", mappedBy="Eleve", cascade={"persist"})
     */
    private $Parent;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Classe", inversedBy="eleve")
     * @ORM\JoinColumn(nullable=true)
     */
    private $classe;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Option", inversedBy="Eleves")
     */
    private $Options;









    public function __construct()
    {
        $this->Classe = new ArrayCollection();
        $this->Parent = new ArrayCollection();
        $this->Options = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }

    public function getPrenoms(): ?string
    {
        return $this->Prenoms;
    }

    public function setPrenoms(string $Prenoms): self
    {
        $this->Prenoms = $Prenoms;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPaysDeNaissance(): ?string
    {
        return $this->PaysDeNaissance;
    }

    public function setPaysDeNaissance(string $PaysDeNaissance): self
    {
        $this->PaysDeNaissance = $PaysDeNaissance;

        return $this;
    }

    public function getLieuDeNaissance(): ?string
    {
        return $this->LieuDeNaissance;
    }

    public function setLieuDeNaissance(string $LieuDeNaissance): self
    {
        $this->LieuDeNaissance = $LieuDeNaissance;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->DateDeNaissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $DateDeNaissance): self
    {
        $this->DateDeNaissance = $DateDeNaissance;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->Sexe;
    }

    public function setSexe(string $Sexe): self
    {
        $this->Sexe = $Sexe;

        return $this;
    }

    public function getAdresseDeResidence(): ?string
    {
        return $this->AdresseDeResidence;
    }

    public function setAdresseDeResidence(string $AdresseDeResidence): self
    {
        $this->AdresseDeResidence = $AdresseDeResidence;

        return $this;
    }

    public function getTelephoneDomicile(): ?int
    {
        return $this->TelephoneDomicile;
    }

    public function setTelephoneDomicile(int $TelephoneDomicile): self
    {
        $this->TelephoneDomicile = $TelephoneDomicile;

        return $this;
    }

    public function getTelephoneEleve(): ?int
    {
        return $this->TelephoneEleve;
    }

    public function setTelephoneEleve(?int $TelephoneEleve): self
    {
        $this->TelephoneEleve = $TelephoneEleve;

        return $this;
    }

    public function getAnneeDarrivee(): ?\DateTimeInterface
    {
        return $this->AnneeDarrivee;
    }

    public function setAnneeDarrivee(\DateTimeInterface $AnneeDarrivee): self
    {
        $this->AnneeDarrivee = $AnneeDarrivee;

        return $this;
    }


    public function getPetitFrereOuSoeur(): ?string
    {
        return $this->PetitFrereOuSoeur;
    }

    public function setPetitFrereOuSoeur(?string $PetitFrereOuSoeur): self
    {
        $this->PetitFrereOuSoeur = $PetitFrereOuSoeur;

        return $this;
    }

    public function getFrereOuSoeur(): ?string
    {
        return $this->FrereOuSoeur;
    }

    public function setFrereOuSoeur(?string $FrereOuSoeur): self
    {
        $this->FrereOuSoeur = $FrereOuSoeur;

        return $this;
    }

    public function getPreferenceManuel(): ?string
    {
        return $this->PreferenceManuel;
    }

    public function setPreferenceManuel(string $PreferenceManuel): self
    {
        $this->PreferenceManuel = $PreferenceManuel;

        return $this;
    }

    public function getTolerenceParacetamol(): ?string
    {
        return $this->TolerenceParacetamol;
    }

    public function setTolerenceParacetamol(string $TolerenceParacetamol): self
    {
        $this->TolerenceParacetamol = $TolerenceParacetamol;

        return $this;
    }

    public function getMaladieSignale(): ?string
    {
        return $this->MaladieSignale;
    }

    public function setMaladieSignale(?string $MaladieSignale): self
    {
        $this->MaladieSignale = $MaladieSignale;

        return $this;
    }

    public function getCodeFamille(): ?int
    {
        return $this->CodeFamille;
    }

    public function setCodeFamille(int $CodeFamille): self
    {
        $this->CodeFamille = $CodeFamille;

        return $this;
    }


    /**
     * @return Collection|Parents[]
     */
    public function getParent(): Collection
    {
        return $this->Parent;
    }

    public function addParent(Parents $parent): self
    {
        if (!$this->Parent->contains($parent)) {
            $this->Parent[] = $parent;
            $parent->setEleve($this);
        }

        return $this;
    }

    public function removeParent(Parents $parent): self
    {
        if ($this->Parent->contains($parent)) {
            $this->Parent->removeElement($parent);
            // set the owning side to null (unless already changed)
            if ($parent->getEleve() === $this) {
                $parent->setEleve(null);
            }
        }

        return $this;
    }

    public function getClasse(): ?Classe
    {
        return $this->classe;
    }

    public function setClasse(?Classe $classe): self
    {
        $this->classe = $classe;

        return $this;
    }

    /**
     * @return Collection|Option[]
     */
    public function getOptions(): Collection
    {
        return $this->Options;
    }

    public function addOption(Option $option): self
    {
        if (!$this->Options->contains($option)) {
            $this->Options[] = $option;
        }

        return $this;
    }

    public function removeOption(Option $option): self
    {
        if ($this->Options->contains($option)) {
            $this->Options->removeElement($option);
        }

        return $this;
    }




}

src/Entity/Salarie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SalarieRepository")
 */
class Salarie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Poste;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TypeDeContract;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $TelephonePortable;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $AdresseDeResidence;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Matricule;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPoste(): ?string
    {
        return $this->Poste;
    }

    public function setPoste(string $Poste): self
    {
        $this->Poste = $Poste;

        return $this;
    }

    public function getTypeDeContract(): ?string
    {
        return $this->TypeDeContract;
    }

    public function setTypeDeContract(string $TypeDeContract): self
    {
        $this->TypeDeContract = $TypeDeContract;

        return $this;
    }

    public function getTelephonePortable(): ?string
    {
        return $this->TelephonePortable;
    }

    public function setTelephonePortable(string $TelephonePortable): self
    {
        $this->TelephonePortable = $TelephonePortable;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getAdresseDeResidence(): ?string
    {
        return $this->AdresseDeResidence;
    }

    public function setAdresseDeResidence(string $AdresseDeResidence): self
    {
        $this->AdresseDeResidence = $AdresseDeResidence;

        return $this;
    }

    public function getMatricule(): ?string
    {
        return $this->Matricule;
    }

    public function setMatricule(string $Matricule): self
    {
        $this->Matricule = $Matricule;

        return $this;
    }
}

templates/pages/login.html.twig
{% extends 'base.html.twig' %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Wk - Facturation Rahma</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{ path('homepage') }}">Accueil <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('Login') }}">connexion</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('dashboard') }}">dashboard</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('homepage') }}">Déconnexion</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
    {% endblock %}
{% block stylesheets %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="style/images/icons/favicon.ico"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="style/css/util.css">
    <link rel="stylesheet" type="text/css" href="style/css/main.css">
    <!--===============================================================================================-->

{% endblock %}

{% block body %}
<div class="limiter">
    <div class="container-login100">
        <div class="wrap-login100 p-t-50 p-b-90">
            <form class="login100-form validate-form flex-sb flex-w">
					<span class="login100-form-title p-b-51">
						Login
					</span>


                <div class="wrap-input100 validate-input m-b-16" data-validate = "Username is required">
                    <input class="input100" type="text" name="username" placeholder="Username">
                    <span class="focus-input100"></span>
                </div>


                <div class="wrap-input100 validate-input m-b-16" data-validate = "Password is required">
                    <input class="input100" type="password" name="pass" placeholder="Password">
                    <span class="focus-input100"></span>
                </div>

                <div class="flex-sb-m w-full p-t-3 p-b-24">
                    <div class="contact100-form-checkbox">
                        <input class="input-checkbox100" id="ckb1" type="checkbox" name="remember-me">
                        <label class="label-checkbox100" for="ckb1">
                            Remember me
                        </label>
                    </div>

                    <div>
                        <a href="#" class="txt1">
                            Forgot?
                        </a>
                    </div>
                </div>

                <div class="container-login100-form-btn m-t-17">
                    <button class="login100-form-btn">
                        Login
                    </button>
                </div>

            </form>
        </div>
    </div>
</div>


<!--===============================================================================================-->
<script src="style/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
<script src="style/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
<script src="style/vendor/bootstrap/js/popper.js"></script>
<script src="style/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
<script src="style/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
<script src="style/vendor/daterangepicker/moment.min.js"></script>
<script src="style/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
<script src="style/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
<script src="style/js/main.js"></script>
{% endblock %}

templates/pages/login2.html.twig
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>
<body class="bg-gradient-primary">

<div class="container">

    <!-- Outer Row -->

    <div class="row justify-content-center mt-5">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-log-img" style="background-image: url(bpic.jpg)" ></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Bienvenue !</h1>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <input type="text" class="form-control form-control-user" id="exampleInputEmail" aria-describedby="nom d'utilisateur" placeholder="Entrer votre nom d'utilisateur...">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user" id="exampleInputPassword" placeholder="Mot de passe">
                                    </div>
                                    <div class="form-group">

                                    </div>
                                    <a href="index.html" class="btn btn-primary btn-user btn-block">
                                        Login
                                    </a>
                                    <hr>

                                </form>
                                <hr>

                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>

<!-- Bootstrap core JavaScript-->
<script src="vendor/jquery/jquery.min.js"></script>
<script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- Core plugin JavaScript-->
<script src="vendor/jquery-easing/jquery.easing.min.js"></script>

<!-- Custom scripts for all pages-->
<script src="js/sb-admin-2.min.js"></script>
</body>
</html>

templates/pages/maindashboard.html.twig
{% extends 'dashboardbase.html.twig' %}

{% block title %} Wk- RahmahTool Facturation dashboard {% endblock %}


{% block body %}

    <div class="container-fluid mb-4">
        <div class="d-inline-flex">
            <h2> Bienvenue {{ app.user.prenom }} {{ app.user.nom }}</h2>
            <p class="d-inline-flex ml-5 btn btn-danger  "><i class="far fa-calendar-alt mr-2"></i>  {{ "now"|date("d/m/Y") }}
                <i class="far fa-clock mr-2 ml-3"></i> {{ "now"|date('H:i:s') }}</p>
        </div>
        <div class="row mt-4">
            <div class="col">
                <div class="card bg-gradient-dark text-white mb-3 text-center">
                    <div class="card-body">
                        <div class="row">
                            <div class="col4">
                                <i class="fas fa-user fa-3x p-2 "></i>                             </div>
                            <div class="col-8">
                                <h5 class="card-title"> {{ stats.eleve}} eleves inscris</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card bg-gradient-dark text-white mb-3 text-center">
                    <div class="card-body">
                        <div class="row">
                            <div class="col4">
                                <i class="fas fa-columns fa-3x p-2 "></i>                            </div>
                            <div class="col-8">
                                <h5 class="card-title"> {{ stats.classe }} Classes disponibles</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card bg-gradient-dark text-white mb-3 text-center">
                    <div class="card-body">
                        <div class="row">
                            <div class="col4">
                                <i class="fas fa-user-friends fa-3x p-2"></i>
                            </div>
                            <div class="col-8">
                                <h5 class="card-title"> {{ stats.parents }} Parents Enregistrés </h5>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card bg-gradient-dark text-white mb-3 text-center">
                    <div class="card-body">
                        <div class="row">
                            <div class="col4">
                                <i class="fas fa-users fa-3x p-2"></i>
                            </div>
                            <div class="col-8">
                                <h5 class="card-title"> {{stats.employe}} Personnes Employés  </h5>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<div class="row container-fluid mt-2 mb-4 ">
    <div class="col-6">
        <div class=" bg-gradient-success shadow">
            <h4 class="text-white p-3"> Dernieres Incriptions </h4>
            <div>
                <table class="table table-hover bg-light">
                    <thead>
                    <tr>
                        <th class=""> Classe </th>
                        <th> Prenom </th>
                        <th> Nom </th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for eleve in insrecent %}
                        <tr>
                            <td> {{ eleve.classe.classe }} </td>
                            <td> {{ eleve.prenoms }} </td>
                            <td> {{ eleve.nom }}  </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div> <br>
        </div>
    </div>
    <div class="col-6">
        <div class=" bg-gradient-success shadow">
            <h4 class="text-white p-3"> Derniers Recrutements </h4>
            <div>
                <table class="table table-hover bg-light">
                    <thead>
                    <tr>
                        <th class=""> Poste </th>
                        <th> Prenom </th>
                        <th> Nom </th>
                        <th> type de Contrat </th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for salarie in recRecent %}
                        <tr>
                            <td> {{ salarie.Poste }} </td>
                            <td> {{ salarie.Prenom }} </td>
                            <td> {{ salarie.nom }}  </td>
                            <td> {{ salarie.TypeDeContract }}  </td>

                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

            </div> <br>
        </div>
    </div>
</div>

    <div class="row container-fluid mt-2 ">
        <div class="col mt-4">
            <div class=" shadow mt-2 p-2">
                <h3 class=" p-2 text-success" > <i class="fas fa-money-check "></i> Derniers Paiements </h3>
                <div>
                    <table class="table table-hover bg-light">
                        <thead>
                        <tr>
                            <th class=""> service </th>
                            <th> type </th>
                            <th> Eleve </th>
                            <th> classe </th>
                            <th> Montant</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for eleve in insrecent %}
                            <tr>
                                <td> vide </td>
                                <td> vide </td>
                                <td> vide  </td>
                                <td> vide  </td>
                                <td> vide  </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div> <br>
            </div>
        </div>

    </div>
    <div class="row container-fluid mt-2 ">
        <div class="col mt-4">
            <div class=" shadow mt-2 p-2">
                <h3 class=" p-2 text-success" > <i class="fas fa-money-check "></i> Dernieres Depenses </h3>
                <div>
                    <table class="table table-hover bg-light" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th class=""> service </th>
                            <th> Object </th>
                            <th> montant </th>
                            <th> description </th>
                            <th> Montant</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for eleve in insrecent %}
                            <tr>
                                <td> vide </td>
                                <td> vide </td>
                                <td> vide  </td>
                                <td> vide  </td>
                                <td> vide  </td>

                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div> <br>
            </div>
        </div>

    </div>



{% endblock %}